services:
  valheim:
    image: ghcr.io/lloesche/valheim-server
    container_name: "valheim"
    cap_add:
      - sys_nice
    volumes:
      - $HOME/valheim-server-modded/config:/config
      - $HOME/valheim-server-modded/data:/opt/valheim
    ports:
      - "2456-2458:2456-2458/udp"
      - "9001:9001/tcp"
    env_file:
      - .env
    restart: always
    stop_grace_period: 2m
